CREATE TABLE `todo`(
 `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT , 
 `title` CHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , 
 `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , 
 `complete` BOOLEAN NOT NULL DEFAULT 0, 
 `postTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;